[package]
name = "gesh"
version = "0.1.0"
authors = ["Jason Gedge <jason.gedge@shopify.com>"]

[dependencies]
geshl = { version = "0.1.0", path = "./gesh-geshl" }

dirs = "1.0.2"
glob = "0.2.11"
rustyline = "1.0.0"

[workspace]
members = [
  ".",
  "gesh-geshl",
]
